/*
CREATED: 19/7/2017
MODIFIED: 25/9/2026
MODEL: UNAPLANILLA
DATABASE: ORACLE 11G RELEASE 2
*/
-- CREATE SEQUENCES SECTION -------------------------------------------------
CREATE SEQUENCE PLAM_TIPOPLANILLAS_SEQ01
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 MINVALUE 0
 NOCACHE
/
CREATE SEQUENCE PLAM_EMPLEADOS_SEQ01
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 MINVALUE 0
 NOCACHE
/
CREATE SEQUENCE PLAM_BANCOS_SEQ01
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 MINVALUE 0
 NOCACHE
/
CREATE SEQUENCE PLAM_CUENTASBANCARIAS_SEQ01
 INCREMENT BY 1
 START WITH 1
 NOMAXVALUE
 MINVALUE 0
 NOCACHE
/
-- CREATE TABLES SECTION -------------------------------------------------
-- TABLE PLAM_EMPLEADOS
CREATE TABLE PLAM_EMPLEADOS(
  EMP_ID NUMBER NOT NULL,
  EMP_NOMBRE VARCHAR2(30 ) NOT NULL,
  EMP_PAPELLIDO VARCHAR2(15 ) NOT NULL,
  EMP_SAPELLIDO VARCHAR2(15 ),
  EMP_CEDULA VARCHAR2(40 ) NOT NULL,
  EMP_GENERO VARCHAR2(1 ) DEFAULT 'M' NOT NULL
        CONSTRAINT PLAM_EMPLEADOS_CK03 CHECK (EMP_GENERO IN ('M','F')),
  EMP_CORREO VARCHAR2(80 ),
  EMP_ADMINISTRADOR VARCHAR2(1 ) DEFAULT 'N' NOT NULL
        CONSTRAINT PLAM_EMPLEADOS_CK02 CHECK (EMP_ADMINISTRADOR IN ('S','N')),
  EMP_USUARIO VARCHAR2(15 ),
  EMP_CLAVE VARCHAR2(8 ),
  EMP_FINGRESO DATE NOT NULL,
  EMP_FSALIDA DATE,
  EMP_ESTADO VARCHAR2(1 ) DEFAULT 'A' NOT NULL
        CONSTRAINT PLAM_EMPLEADOS_CK01 CHECK (EMP_ESTADO IN ('A','I')),
  EMP_VERSION NUMBER DEFAULT 1 NOT NULL
)
/
-- CREATE INDEXES FOR TABLE PLAM_EMPLEADOS
CREATE UNIQUE INDEX PLAM_EMPLEADOS_IND01 ON PLAM_EMPLEADOS (EMP_USUARIO)
/
CREATE UNIQUE INDEX PLAM_EMPLEADOS_IND02 ON PLAM_EMPLEADOS (EMP_CEDULA)
/
-- ADD KEYS FOR TABLE PLAM_EMPLEADOS
ALTER TABLE PLAM_EMPLEADOS ADD CONSTRAINT PLAM_EMPLEADOS_PK PRIMARY KEY (EMP_ID)
/
-- TABLE AND COLUMNS COMMENTS SECTION
COMMENT ON TABLE PLAM_EMPLEADOS IS 'TABLA DE EMPLEADOS'
/
COMMENT ON COLUMN PLAM_EMPLEADOS.EMP_ID IS 'ID DEL EMPLEADO'
/
COMMENT ON COLUMN PLAM_EMPLEADOS.EMP_NOMBRE IS 'NOMBRE DEL EMPLEADO'
/
COMMENT ON COLUMN PLAM_EMPLEADOS.EMP_PAPELLIDO IS 'PRIMER APELLIDO DEL EMPLEADO'
/
COMMENT ON COLUMN PLAM_EMPLEADOS.EMP_SAPELLIDO IS 'SEGUNDO APELLIDO DEL EMPLEADO'
/
COMMENT ON COLUMN PLAM_EMPLEADOS.EMP_CEDULA IS 'CEDULA DEL EMPLEADO'
/
COMMENT ON COLUMN PLAM_EMPLEADOS.EMP_GENERO IS 'GENERO DEL EMPLEADO (M:MASCULINO, F:FEMENINO)'
/
COMMENT ON COLUMN PLAM_EMPLEADOS.EMP_CORREO IS 'CORREO ELECTRONICO DEL EMPLEADO'
/
COMMENT ON COLUMN PLAM_EMPLEADOS.EMP_ADMINISTRADOR IS 'EMPLEADO ADMINISTADOR DEL SISTEMA (S:SI, N:NO)'
/
COMMENT ON COLUMN PLAM_EMPLEADOS.EMP_USUARIO IS 'USUARIO DEL SISTEMA PARA EL EMPLEADO'
/
COMMENT ON COLUMN PLAM_EMPLEADOS.EMP_CLAVE IS 'CLAVE DEL SISTEMA PARA EL EMPLEADO'
/
COMMENT ON COLUMN PLAM_EMPLEADOS.EMP_FINGRESO IS 'FECHA DE INGRESO DEL EMPLEADO'
/
COMMENT ON COLUMN PLAM_EMPLEADOS.EMP_FSALIDA IS 'FECHA DE SALIDA DEL EMPLEADO'
/
COMMENT ON COLUMN PLAM_EMPLEADOS.EMP_ESTADO IS 'ESTADO DEL EMPLEADO (A:ACTIVO, I:INACTIVO)'
/
COMMENT ON COLUMN PLAM_EMPLEADOS.EMP_VERSION IS 'VERSION DEL REGISTRO'
/
-- TABLE PLAM_TIPOPLANILLAS
CREATE TABLE PLAM_TIPOPLANILLAS(
  TPLA_ID NUMBER NOT NULL,
  TPLA_CODIGO VARCHAR2(4 ) NOT NULL,
  TPLA_DESCRIPCION VARCHAR2(40 ) NOT NULL,
  TPLA_PLAXMES NUMBER NOT NULL,
  TPLA_ANOULTPLA NUMBER,
  TPLA_MESULTPLA NUMBER,
  TPLA_NUMULTPLA NUMBER,
  TPLA_ESTADO VARCHAR2(1 ) DEFAULT 'A' NOT NULL
        CONSTRAINT PLAM_TIPOPLANILLAS_CK01 CHECK (TPLA_ESTADO IN ('A','I')),
  TPLA_VERSION NUMBER DEFAULT 1 NOT NULL
)
/
-- CREATE INDEXES FOR TABLE PLAM_TIPOPLANILLAS
CREATE UNIQUE INDEX PLAM_TIPOPLANILLAS_IND01 ON PLAM_TIPOPLANILLAS (TPLA_CODIGO)
/
-- ADD KEYS FOR TABLE PLAM_TIPOPLANILLAS
ALTER TABLE PLAM_TIPOPLANILLAS ADD CONSTRAINT PLAM_TIPOPLANILLAS_PK PRIMARY KEY (TPLA_ID)
/
-- TABLE AND COLUMNS COMMENTS SECTION
COMMENT ON TABLE PLAM_TIPOPLANILLAS IS 'TABLA DE TIPOS DE PLANILLA'
/
COMMENT ON COLUMN PLAM_TIPOPLANILLAS.TPLA_ID IS 'ID DEL TIPO DE PLANILLA'
/
COMMENT ON COLUMN PLAM_TIPOPLANILLAS.TPLA_CODIGO IS 'CODIGO DEL TIPO DE PLANILLA'
/
COMMENT ON COLUMN PLAM_TIPOPLANILLAS.TPLA_DESCRIPCION IS 'DESCRIPCION O NOMBRE DE LA PLANILLA'
/
COMMENT ON COLUMN PLAM_TIPOPLANILLAS.TPLA_PLAXMES IS 'CANTIDAD DE PLANILLAS A GENERAR POR MES'
/
COMMENT ON COLUMN PLAM_TIPOPLANILLAS.TPLA_ANOULTPLA IS 'AÑO DE LA ULTIMA PLANILLA GENERADA'
/
COMMENT ON COLUMN PLAM_TIPOPLANILLAS.TPLA_MESULTPLA IS 'MES DE LA ULTIMA PLANILLA GENERADA'
/
COMMENT ON COLUMN PLAM_TIPOPLANILLAS.TPLA_NUMULTPLA IS 'NUMERO DE LA ULTIMA PLANILLA GENERADA'
/
COMMENT ON COLUMN PLAM_TIPOPLANILLAS.TPLA_ESTADO IS 'ESTADO DEL TIPO DE PLANILLA(A:ACTIVA,I:INACTIVA)'
/
COMMENT ON COLUMN PLAM_TIPOPLANILLAS.TPLA_VERSION IS 'VERSION DEL REGISTRO'
/
-- TABLE PLAM_EMPLEADOSPLANILLA
CREATE TABLE PLAM_EMPLEADOSPLANILLA(
  EXP_IDTPLA NUMBER NOT NULL,
  EXP_IDEMP NUMBER NOT NULL
)
/
-- ADD KEYS FOR TABLE PLAM_EMPLEADOSPLANILLA
ALTER TABLE PLAM_EMPLEADOSPLANILLA ADD CONSTRAINT PLAM_EMPLEADOSPLANILLA_PK PRIMARY KEY (EXP_IDTPLA,EXP_IDEMP)
/
-- TABLE AND COLUMNS COMMENTS SECTION
COMMENT ON TABLE PLAM_EMPLEADOSPLANILLA IS 'TABLA RALACIONAL DE EMPLEADOS POR TIPO DE PLANILLA'
/
COMMENT ON COLUMN PLAM_EMPLEADOSPLANILLA.EXP_IDTPLA IS 'ID DEL TIPO DE PLANILLA.'
/
COMMENT ON COLUMN PLAM_EMPLEADOSPLANILLA.EXP_IDEMP IS 'ID DEL EMPLEADO.'
/
-- TABLE PLAM_BANCOS
CREATE TABLE PLAM_BANCOS(
  BAN_ID NUMBER NOT NULL,
  BAN_NOMBRE VARCHAR2(80 ) NOT NULL,
  BAN_REBAJOCOMISION VARCHAR2(1 ) NOT NULL
        CONSTRAINT PLAM_BANCOS_CK01 CHECK (BAN_REBAJOCOMISION IN ('E','M')),
  BAN_COMISIONTRAN NUMBER NOT NULL,
  BAN_ESTADO VARCHAR2(1 ) NOT NULL
        CONSTRAINT PLAM_BANCOS_CK02 CHECK (BAN_ESTADO IN ('A','I')),
  BAN_VERSION NUMBER DEFAULT 1 NOT NULL
)
/
-- ADD KEYS FOR TABLE PLAM_BANCOS
ALTER TABLE PLAM_BANCOS ADD CONSTRAINT PK_PLAM_BANCOS PRIMARY KEY (BAN_ID)
/
-- TABLE AND COLUMNS COMMENTS SECTION
COMMENT ON TABLE PLAM_BANCOS IS 'TABLA DE BANCOS'
/
COMMENT ON COLUMN PLAM_BANCOS.BAN_ID IS 'ID DEL BANCO'
/
COMMENT ON COLUMN PLAM_BANCOS.BAN_NOMBRE IS 'NOMBRE DEL BANCO'
/
COMMENT ON COLUMN PLAM_BANCOS.BAN_REBAJOCOMISION IS 'INDICA QUIEN CUBRE LA COMISION DE LA TRANSFERENCIA (E: EMPLEADO, M: EMPRESA)'
/
COMMENT ON COLUMN PLAM_BANCOS.BAN_COMISIONTRAN IS 'MONTO DE LA COMISION POR TRANSFERENCIA ELECTRONICA'
/
COMMENT ON COLUMN PLAM_BANCOS.BAN_ESTADO IS 'INDICA EL ESTADO DEL BANCO (A: ACTIVO, I: INACTIVO)'
/
COMMENT ON COLUMN PLAM_BANCOS.BAN_VERSION IS 'VERSION DEL REGISTRO'
/
-- TABLE PLAM_CUENTASBANCARIAS
CREATE TABLE PLAM_CUENTASBANCARIAS(
  CBE_ID NUMBER NOT NULL,
  CBE_IDEMP NUMBER NOT NULL,
  CBE_IDBAN NUMBER NOT NULL,
  CBE_AGENCIA NUMBER NOT NULL,
  CBE_ADICIONAL NUMBER,
  CBE_NUMEROCUENTA NUMBER NOT NULL,
  CBE_TIPO VARCHAR2(1 ) NOT NULL
        CONSTRAINT PLAM_CUENTASBANCARIAS_CK01 CHECK (CBE_TIPO IN ('C','A')),
  CBE_PRINCIPAL VARCHAR2(1 ) NOT NULL
        CONSTRAINT PLAM_CUENTASBANCARIAS_CK02 CHECK (CBE_PRINCIPAL IN ('S','N')),
  CBE_VERSION NUMBER DEFAULT 1 NOT NULL
)
/
-- CREATE INDEXES FOR TABLE PLAM_CUENTASBANCARIAS
CREATE INDEX PLAM_CUENTASBANCARIAS_IND01 ON PLAM_CUENTASBANCARIAS (CBE_IDEMP)
/
CREATE INDEX PLAM_CUENTASBANCARIAS_IND02 ON PLAM_CUENTASBANCARIAS (CBE_IDBAN)
/
CREATE UNIQUE INDEX PLAM_CUENTASBANCARIAS_IND03 ON PLAM_CUENTASBANCARIAS (CBE_IDBAN, CBE_NUMEROCUENTA)
/
-- ADD KEYS FOR TABLE PLAM_CUENTASBANCARIAS
ALTER TABLE PLAM_CUENTASBANCARIAS ADD CONSTRAINT PK_PLAM_CUENTASBANCARIAS PRIMARY KEY (CBE_ID)
/
-- TABLE AND COLUMNS COMMENTS SECTION
COMMENT ON TABLE PLAM_CUENTASBANCARIAS IS 'TABLA DE CUENTAS BANCARIAS'
/
COMMENT ON COLUMN PLAM_CUENTASBANCARIAS.CBE_ID IS 'ID DE LA CUENTA BANCARIA'
/
COMMENT ON COLUMN PLAM_CUENTASBANCARIAS.CBE_IDEMP IS 'ID DEL EMPLEADO'
/
COMMENT ON COLUMN PLAM_CUENTASBANCARIAS.CBE_IDBAN IS 'ID DEL BANCO'
/
COMMENT ON COLUMN PLAM_CUENTASBANCARIAS.CBE_AGENCIA IS 'CODIGO DE LA AGENCIA'
/
COMMENT ON COLUMN PLAM_CUENTASBANCARIAS.CBE_ADICIONAL IS 'CODIGO ADICIONAL DE LA CUENTA BANCARIA'
/
COMMENT ON COLUMN PLAM_CUENTASBANCARIAS.CBE_NUMEROCUENTA IS 'NUMERO DE CUENTA BANCARIA'
/
COMMENT ON COLUMN PLAM_CUENTASBANCARIAS.CBE_TIPO IS 'TIPO DE CUENTA (C: CORRIENTE, A: AHORROS)'
/
COMMENT ON COLUMN PLAM_CUENTASBANCARIAS.CBE_PRINCIPAL IS 'INDICA SI ES LA CUENTA PRINCIPAL DEL EMPLEADO (S: SI, N: NO)'
/
COMMENT ON COLUMN PLAM_CUENTASBANCARIAS.CBE_VERSION IS 'VERSION DEL REGISTRO'
/
-- TRIGGER FOR SEQUENCE PLAM_EMPLEADOS_SEQ01 FOR COLUMN EMP_ID IN TABLE PLAM_EMPLEADOS ---------
CREATE OR REPLACE TRIGGER TS_PLAM_EMPLEADOS_PLAM_EMPLE_0 BEFORE INSERT
ON PLAM_EMPLEADOS FOR EACH ROW
BEGIN
  IF :NEW.EMP_ID IS NULL THEN
    :NEW.EMP_ID := PLAM_EMPLEADOS_SEQ01.NEXTVAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER TSU_PLAM_EMPLEADOS_PLAM_EMPL_0 AFTER UPDATE OF EMP_ID
ON PLAM_EMPLEADOS FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20010,'CANNOT UPDATE COLUMN EMP_ID IN TABLE PLAM_EMPLEADOS AS IT USES SEQUENCE.');
END;
/
-- TRIGGER TO AUTO-INCREMENT EMP_VERSION ON EVERY UPDATE
CREATE OR REPLACE TRIGGER TV_PLAM_EMPLEADOS_VERSION BEFORE UPDATE
ON PLAM_EMPLEADOS FOR EACH ROW
BEGIN
  :NEW.EMP_VERSION := :OLD.EMP_VERSION + 1;
END;
/
-- TRIGGER FOR SEQUENCE PLAM_TIPOPLANILLAS_SEQ01 FOR COLUMN TPLA_ID IN TABLE PLAM_TIPOPLANILLAS ---------
CREATE OR REPLACE TRIGGER TS_PLAM_TIPOPLANILLAS_PLAM_T_0 BEFORE INSERT
ON PLAM_TIPOPLANILLAS FOR EACH ROW
BEGIN
  IF :NEW.TPLA_ID IS NULL THEN
    :NEW.TPLA_ID := PLAM_TIPOPLANILLAS_SEQ01.NEXTVAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER TSU_PLAM_TIPOPLANILLAS_PLAM__0 AFTER UPDATE OF TPLA_ID
ON PLAM_TIPOPLANILLAS FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20010,'CANNOT UPDATE COLUMN TPLA_ID IN TABLE PLAM_TIPOPLANILLAS AS IT USES SEQUENCE.');
END;
/
-- TRIGGER TO AUTO-INCREMENT TPLA_VERSION ON EVERY UPDATE
CREATE OR REPLACE TRIGGER TV_PLAM_TIPOPLANILLAS_VERSION BEFORE UPDATE
ON PLAM_TIPOPLANILLAS FOR EACH ROW
BEGIN
  :NEW.TPLA_VERSION := :OLD.TPLA_VERSION + 1;
END;
/
-- TRIGGER FOR SEQUENCE PLAM_BANCOS_SEQ01 FOR COLUMN BAN_ID IN TABLE PLAM_BANCOS ---------
CREATE OR REPLACE TRIGGER TS_PLAM_BANCOS_PLAM_BANCOS_S_0 BEFORE INSERT
ON PLAM_BANCOS FOR EACH ROW
BEGIN
  IF :NEW.BAN_ID IS NULL THEN
    :NEW.BAN_ID := PLAM_BANCOS_SEQ01.NEXTVAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER TSU_PLAM_BANCOS_PLAM_BANCOS__0 AFTER UPDATE OF BAN_ID
ON PLAM_BANCOS FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20010,'CANNOT UPDATE COLUMN BAN_ID IN TABLE PLAM_BANCOS AS IT USES SEQUENCE.');
END;
/
-- TRIGGER TO AUTO-INCREMENT BAN_VERSION ON EVERY UPDATE
CREATE OR REPLACE TRIGGER TV_PLAM_BANCOS_VERSION BEFORE UPDATE
ON PLAM_BANCOS FOR EACH ROW
BEGIN
  :NEW.BAN_VERSION := :OLD.BAN_VERSION + 1;
END;
/
-- TRIGGER FOR SEQUENCE PLAM_CUENTASBANCARIAS_SEQ01 FOR COLUMN CBE_ID IN TABLE PLAM_CUENTASBANCARIAS ---------
CREATE OR REPLACE TRIGGER TS_PLAM_CUENTASBANCARIAS_PLA_0 BEFORE INSERT
ON PLAM_CUENTASBANCARIAS FOR EACH ROW
BEGIN
  IF :NEW.CBE_ID IS NULL THEN
    :NEW.CBE_ID := PLAM_CUENTASBANCARIAS_SEQ01.NEXTVAL;
  END IF;
END;
/
CREATE OR REPLACE TRIGGER TSU_PLAM_CUENTASBANCARIAS_PL_0 AFTER UPDATE OF CBE_ID
ON PLAM_CUENTASBANCARIAS FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20010,'CANNOT UPDATE COLUMN CBE_ID IN TABLE PLAM_CUENTASBANCARIAS AS IT USES SEQUENCE.');
END;
/
-- TRIGGER TO AUTO-INCREMENT CBE_VERSION ON EVERY UPDATE
CREATE OR REPLACE TRIGGER TV_PLAM_CUENTASBANCARIAS_VERSION BEFORE UPDATE
ON PLAM_CUENTASBANCARIAS FOR EACH ROW
BEGIN
  :NEW.CBE_VERSION := :OLD.CBE_VERSION + 1;
END;
/
-- CREATE FOREIGN KEYS (RELATIONSHIPS) SECTION ------------------------------------------------- 
ALTER TABLE PLAM_EMPLEADOSPLANILLA ADD CONSTRAINT PLAM_EMPLEADOSPLANILLA_FK01 FOREIGN KEY (EXP_IDTPLA) REFERENCES PLAM_TIPOPLANILLAS (TPLA_ID)
/
ALTER TABLE PLAM_EMPLEADOSPLANILLA ADD CONSTRAINT PLAM_EMPLEADOSPLANILLA_FK02 FOREIGN KEY (EXP_IDEMP) REFERENCES PLAM_EMPLEADOS (EMP_ID)
/
ALTER TABLE PLAM_CUENTASBANCARIAS ADD CONSTRAINT PLAM_CUENTASBANCARIAS_FK01 FOREIGN KEY (CBE_IDEMP) REFERENCES PLAM_EMPLEADOS (EMP_ID)
/
ALTER TABLE PLAM_CUENTASBANCARIAS ADD CONSTRAINT PLAM_CUENTASBANCARIAS_FK02 FOREIGN KEY (CBE_IDBAN) REFERENCES PLAM_BANCOS (BAN_ID)
/