BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PLAM_CUENTASBANCARIAS DROP CONSTRAINT PLAM_CUENTASBANCARIAS_FK01';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PLAM_CUENTASBANCARIAS DROP CONSTRAINT PLAM_CUENTASBANCARIAS_FK02';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PLAM_EMPLEADOSPLANILLA DROP CONSTRAINT PLAM_EMPLEADOSPLANILLA_FK01';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PLAM_EMPLEADOSPLANILLA DROP CONSTRAINT PLAM_EMPLEADOSPLANILLA_FK02';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PLAM_CUENTASBANCARIAS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PLAM_EMPLEADOSPLANILLA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PLAM_EMPLEADOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PLAM_TIPOPLANILLAS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PLAM_BANCOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE PLAM_CUENTASBANCARIAS_SEQ01';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE PLAM_EMPLEADOS_SEQ01';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE PLAM_TIPOPLANILLAS_SEQ01';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE PLAM_BANCOS_SEQ01';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/